if: tag IS present
language: go
os:
  - linux
  - osx
  - windows
go:
  - 1.13.3
addons:
  apt:
    packages:
      - libx11-dev
      - mesa-common-dev
      - libglfw3-dev
      - libgles2-mesa-dev
      - libasound2-dev
script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; choco install 7zip.portable ; fi
  - mkdir -p ./opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME
  - go get
  - go build .
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cp ./OpenDiablo2.exe ./opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME ; else cp ./OpenDiablo2 ./opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME; fi
  - cp ./config.json ./opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then 7z a -r opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME.zip ./opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME ; else tar -cvzf opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME.tar.gz ./opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME ; fi
git:
  depth: 1
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: "$GithubApi"
  file_glob: true

  file: opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME.*
  skip_cleanup: true
  overwrite: true
  name: "OpenDiablo Unstable (Build $TRAVIS_BUILD_NUMBER)"
  prerelease: true
  on:
    tags: true
