version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: x64
before_build:
- cmd: nuget restore OpenDiablo2.sln
build:
  verbosity: minimal
after_build:
- cmd: >-
    cd OpenDiablo2\bin\x64\Release\*
    
    7z a OpenDiablo2-Win64-Dev.zip *
artifacts:
- path: OpenDiablo2\bin\x64\Release\OpenDiablo2-Win64-Dev.zip
  name: Win64
deploy:
- provider: GitHub
  tag: v0.1.$(appveyor_build_version)
  release: opendiablo2-dev-win64
  description: Bleeding edge build of OpenDiablo 2.
  auth_token:
    secure: DqQrogjOZ30PiMxrvrLNSJknmP57lBioZDwxT2xL6fsz0MokaAPq/B8oWNG3uX49
  repository: essial/opendiablo2
  artifact: Win64
  prerelease: true
  force_update: true