---
name: build
"on":
    push:
        branches:
            - master
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   name: Set up Go 1.14
                uses: actions/setup-go@v1
                with:
                    go-version: 1.14
                id: go

            -   name: Check out code
                uses: actions/checkout@v1

            -   name: Install dependencies
                run: |
                    sudo apt-get update
                    sudo apt-get install -y xvfb libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl1-mesa-dev libsdl2-dev libasound2-dev > /dev/null 2>&1

            -   name: Run golangci-lint
                continue-on-error: false
                uses: golangci/golangci-lint-action@v1.2.1
                with:
                    version: v1.27

            -   name: Run tests
                env:
                    DISPLAY: ":99.0"
                run: |
                    xvfb-run --auto-servernum go test -v -race ./...

            -   name: Build binary Linux
                run: go build .

            -   name: Build binary Windows
                run: GOOS=windows GOARCH=amd64 go build

            -   name: Make Release
                uses: "marvinpinto/action-automatic-releases@latest"
                with:
                    repo_token: "${{ secrets.GITHUB_TOKEN }}"
                    automatic_release_tag: "latest"
                    prerelease: true
                    title: "Development Build"
                    files: |
                        OpenDiablo2
                        OpenDiablo2.exe
